author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /sacred-harp-a-collection-of
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://readux.ecds.emory.edu/books/readux:tpq2n/pages/readux:v7bkq/single-page/
image_size:
  page:
    height: 629
    width: 1000
  small-thumbnail:
    height: 62
    width: 100
  thumbnail:
    height: 188
    width: 300
permalink: pretty
publication_info:
  author: B. F White (Benjamin Franklin), 1800-1879.
  date: '2020'
  editors:
  - Jesse P. Karlsberg
  tei_xml: tei.xml
  title: 'The Sacred harp : a collection of psalm and hymn tunes, odes, and anthems,
    selected from the most eminent authors, together with nearly one hundred pieces
    never before published ; suited to most metres, and well adapted to churches of
    every denomination, singing schools, and private societies, with plain rules for
    learners, an annotated digital edition'
show_annotation_author: true
source_info:
  author: B. F White (Benjamin Franklin), 1800-1879.
  date: '1870'
  pdf_url: https://readux.ecds.emory.edu/books/readux:tpq2n/pdf/
  title: 'The Sacred harp : a collection of psalm and hymn tunes, odes, and anthems,
    selected from the most eminent authors, together with nearly one hundred pieces
    never before published ; suited to most metres, and well adapted to churches of
    every denomination, singing schools, and private societies, with plain rules for
    learners'
  url: https://readux.ecds.emory.edu/books/readux:tpq2n/
  via_readux: true
tagline: ', an annotated digital edition'
title: 'The Sacred harp : a collection of psalm and hymn tunes, odes, and anthems,
  selected from the most eminent authors, together with nearly one hundred pieces
  never before published ; suited to most metres, and well adapted to churches of
  every denomination, singing schools, and private societies, with plain rules for
  learners'
url: https://jpkarlsberg.github.io
version: 0.7
